### ISSUE TITLE
Error: unknown shorthand flag: 'a' in -adapter=caddyfile

### ISSUE THREAD

**Issue by gboudreau** [dockhippie/php-caddy#34]
```
$ docker run --rm webhippie/php-caddy:8
...
> starting php service
> starting caddy service
Error: unknown shorthand flag: 'a' in -adapter=caddyfile
```

Caddy started requiring double-dash for parameters. I guess your Caddy image needs to be updated..?

**Comment by tboerger** [comment]
I'm waiting for finishing an updated build of my Caddy image, after that Renovate will take care about updating the base image reference which will resolve the issue. Thanks for reporting this.

**Comment by tboerger** [comment]
Problem have been solved, I had to rename all the packages as well because the php packages have been moved to testing by alpine.
